### ISSUE TITLE
Interested in update?

### ISSUE THREAD

**Issue by heubergen** [andrey-zotov/ib_console#3]
I just found your project and it sounds interesting to me. Would you merge a PR if I update the dependencies, fix any issues because of that and confirm macOS compatibility?

**Comment by andrey-zotov** [comment]
> I just found your project and it sounds interesting to me. Would you merge a PR if I update the dependencies, fix any issues because of that and confirm macOS compatibility?

Sure @heubergen, contributions are welcome!
I might backport other fixes and improvements from a private project if there's an interest.

**Comment by heubergen** [comment]
Thanks, but just realized that this uses the TWS API and not the restAPI, so not really in my scope, sorry.
